[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/claude-proxy"
  to = "/.netlify/functions/claude-proxy"
  status = 200

[[redirects]]
  from = "/api/verify-password"
  to = "/.netlify/functions/verify-password"
  status = 200

[[redirects]]
  from = "/api/data-proxy"
  to = "/.netlify/functions/data-proxy"
  status = 200

[[redirects]]
  from = "/api/news-proxy"
  to = "/.netlify/functions/news-proxy"
  status = 200
